"""empty message

Revision ID: 5c6b6c12dffe
Revises: da026501df2e
Create Date: 2020-07-14 20:37:26.027558

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c6b6c12dffe'
down_revision = 'da026501df2e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('nationality', sa.Column('test', sa.String(length=30), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('nationality', 'test')
    # ### end Alembic commands ###
