"""empty message

Revision ID: 74264c4c171b
Revises: 5c6b6c12dffe
Create Date: 2020-07-14 20:42:36.129287

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '74264c4c171b'
down_revision = '5c6b6c12dffe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('nationality', 'test')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('nationality', sa.Column('test', sa.VARCHAR(length=30), nullable=True))
    # ### end Alembic commands ###
