"""empty message

Revision ID: 364eef423c4b
Revises: 850f203a9213
Create Date: 2020-08-27 14:12:31.144455

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '364eef423c4b'
down_revision = '850f203a9213'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exam_scores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('student', sa.Integer(), nullable=True),
    sa.Column('exam', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['exam'], ['exams.id'], ),
    sa.ForeignKeyConstraint(['student'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_constraint(None, 'class', type_='foreignkey')
    op.drop_column('class', 'user_id')
    op.create_foreign_key(None, 'user', 'class', ['class_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.add_column('class', sa.Column('user_id', sa.INTEGER(), nullable=True))
    op.create_foreign_key(None, 'class', 'user', ['user_id'], ['id'])
    op.drop_table('exam_scores')
    # ### end Alembic commands ###
