"""empty message

Revision ID: 662e07d46522
Revises: 364eef423c4b
Create Date: 2020-08-27 14:41:52.078106

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '662e07d46522'
down_revision = '364eef423c4b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'class', type_='foreignkey')
    op.drop_column('class', 'user_id')
    op.add_column('exams_to_class', sa.Column('is_score_published', sa.Boolean(), nullable=True))
    op.create_foreign_key(None, 'user', 'class', ['class_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_column('exams_to_class', 'is_score_published')
    op.add_column('class', sa.Column('user_id', sa.INTEGER(), nullable=True))
    op.create_foreign_key(None, 'class', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###
