"""empty message

Revision ID: 69052e3a9fd4
Revises: 5483875e136e
Create Date: 2020-08-11 16:40:00.803145

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '69052e3a9fd4'
down_revision = '5483875e136e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('exam_title', sa.String(length=264), nullable=True),
    sa.Column('exam_type', sa.PickleType(), nullable=True),
    sa.Column('level', sa.PickleType(), nullable=True),
    sa.Column('time_for_completion', sa.Float(), nullable=True),
    sa.Column('notion_id', sa.Integer(), nullable=True),
    sa.Column('sub_notion_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['notion_id'], ['notions.id'], ),
    sa.ForeignKeyConstraint(['sub_notion_id'], ['subnotions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('exams_to_questions',
    sa.Column('quest_id', sa.Integer(), nullable=True),
    sa.Column('exam_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['exam_id'], ['exams.id'], ),
    sa.ForeignKeyConstraint(['quest_id'], ['questions.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('exams_to_questions')
    op.drop_table('exams')
    # ### end Alembic commands ###
