"""empty message

Revision ID: 7938902d7e5c
Revises: 662e07d46522
Create Date: 2020-08-27 14:43:53.151321

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7938902d7e5c'
down_revision = '662e07d46522'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'class', type_='foreignkey')
    op.drop_column('class', 'user_id')
    op.add_column('exam_scores', sa.Column('is_score_published', sa.Boolean(), nullable=True))
    op.create_foreign_key(None, 'user', 'class', ['class_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_column('exam_scores', 'is_score_published')
    op.add_column('class', sa.Column('user_id', sa.INTEGER(), nullable=True))
    op.create_foreign_key(None, 'class', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###
