"""empty message

Revision ID: 7c86805bca95
Revises: 
Create Date: 2020-08-10 14:43:27.010796

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c86805bca95'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('notion', sa.String(length=264), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('notion')
    )
    op.create_table('subnotions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sub_notion', sa.String(length=264), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sub_notion')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=264), nullable=True),
    sa.Column('username', sa.String(length=264), nullable=True),
    sa.Column('email', sa.String(length=264), nullable=True),
    sa.Column('password', sa.String(length=264), nullable=True),
    sa.Column('role', sa.PickleType(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question_text', sa.String(), nullable=True),
    sa.Column('type', sa.PickleType(), nullable=True),
    sa.Column('answer', sa.String(), nullable=True),
    sa.Column('wrong_answer1', sa.String(length=264), nullable=True),
    sa.Column('wrong_answer2', sa.String(length=264), nullable=True),
    sa.Column('wrong_answer3', sa.String(length=264), nullable=True),
    sa.Column('notion_id', sa.Integer(), nullable=True),
    sa.Column('sub_notion_id', sa.Integer(), nullable=True),
    sa.Column('is_exam', sa.Boolean(), nullable=True),
    sa.Column('is_test_exam', sa.Boolean(), nullable=True),
    sa.Column('level', sa.PickleType(), nullable=True),
    sa.Column('time_for_completion', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['notion_id'], ['notions.id'], ),
    sa.ForeignKeyConstraint(['sub_notion_id'], ['subnotions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('questions')
    op.drop_table('user')
    op.drop_table('subnotions')
    op.drop_table('notions')
    # ### end Alembic commands ###
