"""empty message

Revision ID: 850f203a9213
Revises: 88adc3278d68
Create Date: 2020-08-22 16:29:33.852009

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '850f203a9213'
down_revision = '88adc3278d68'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exams_to_class',
    sa.Column('exam_id', sa.Integer(), nullable=True),
    sa.Column('class_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['class_id'], ['class.id'], ),
    sa.ForeignKeyConstraint(['exam_id'], ['exams.id'], )
    )
    op.drop_constraint(None, 'class', type_='foreignkey')
    op.drop_column('class', 'user_id')
    op.create_foreign_key(None, 'user', 'class', ['class_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.add_column('class', sa.Column('user_id', sa.INTEGER(), nullable=True))
    op.create_foreign_key(None, 'class', 'user', ['user_id'], ['id'])
    op.drop_table('exams_to_class')
    # ### end Alembic commands ###
