"""empty message

Revision ID: c34039ae7fd5
Revises: 7c86805bca95
Create Date: 2020-08-10 16:56:01.674474

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c34039ae7fd5'
down_revision = '7c86805bca95'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questions', sa.Column('qtype', sa.PickleType(), nullable=True))
    op.add_column('questions', sa.Column('question_title', sa.String(length=264), nullable=True))
    op.drop_column('questions', 'type')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questions', sa.Column('type', sa.BLOB(), nullable=True))
    op.drop_column('questions', 'question_title')
    op.drop_column('questions', 'qtype')
    # ### end Alembic commands ###
